import Header from "@/components/Header";
import Footer from "@/sections/Footer";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shop Center - Buy anything",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
        <Header/>
        {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}